<style>
#pre-sql2{position:absolute;right: 150px;top:20px}
.pre-sql{float:left;font-size:30px;line-height:35px;color:#fff}
.pre-sql:hover{color:#F2F6FB;cursor: pointer}
</style>
<div class="activity clearfix">
    <div class="right_box  in_left clearfix"style="width: 100%;">
    	<!--  start  lable header-->
    	<section class="borders lableContent">
            <div class="aleft_box01" style="position:relative">
	            <ul class=" aleft_ul01 clearfix">
	                <li class="in_left">活动ID：<i id="_id"></i></li>
	                <li>活动名称：<i class="show ellipsis"id="_name">新手大礼包到期</i></li>               
	
	            </ul>
	            <ul class="aleft_ul02 clearfix">
	                <li class="in_left">最新执行日期：<i id="_create_time">20160623</i></li>
	                <li class="in_left" style="width: 25%;">活动状态：<i id="_task_status">执行中</i></li> 
	                <li class="in_left" style="width: 25%;">人群数量：<i id="_list_count"></i></li>             	
	               <!-- <li class="in_right ep2 pointer" id="exportJump" onclick="listExport(this)">名单导出</li>-->
	            </ul>
	            <ul class="aleft_ul03 clearfix">
	               <!-- <li class="in_left"style="font-size: 0.16rem;">已选标签</li>-->
	                
	            </ul>
                    <div id="pre-sql2" class="pre-sql">
                        HQL
                    </div>
	        </div> 
	        <!--  end lable header-->
	        <!--  start lable content-->
	        <div class="lablegroup">  
	            <div id="lableGroup"></div>     
	        </div> 	        
        </section>
        <!--  end lable content-->
        <!-- Filtering the Records -->   
        <div class="entries_group">        
        	<p id="exclude" class="borders"><i>排除活动名单：</i></p>
        </div> 
        <!-- Filtering the Records -->   
        <div class="entries_group">  
        	<p id="contain" class="borders"><i>包含活动名单：</i></p>
        </div>      
        <hr/>
        <!--  start the Activities in query -->
        <article class="borders Activities_in_query">
	        <!--  table nav  -->       
			<nav class="table_nav" style="margin-top: 0.1rem;">
				<ul class="clearfix bottom" style="position: relative;">
					<li class="in_left ma markup" onclick="tabSwitchover(this)"><a href="javascript:;" class="active">券使用情况</a></li>
					<li class="in_left ma" onclick="tabSwitchover(this)"><a href="javascript:;">交易情况</a></li>
					<span id="numberEntries" class="numberEntries"></span>
				</ul>
			</nav>  
			<div class="content_table"style="top: -0.15rem;">											
				<!-- start use situation number  -->
				<section class="table_content showTab"id="use_situation">
					<!--  start table header  -->	
					<section class="table_scroll">		    
						<div class="table-head">
						    <table>
						        <colgroup><col /><col /><col /><col /><col /><col /><col /><col /><col /></colgroup>
						        <thead>
						            <tr class="searchTR">
						        		<th style="border: none;width: auto;"id="issue_stamps"class="coupons">
						        			<i>发放</i>
						        			<input type="text" name="" id="" value="" class="dt startTime" onclick="createDate(this)" onfocus="createDate(this)" placeholder="开始时间" style="max-width:100px ;" />
					        				<i>到</i>
						        			<input type="text" name="" id="" value="" class="dt endTime" onclick="createDate(this)" onfocus="createDate(this)" placeholder="结束时间"  style="max-width:100px ;" />	        		
					        			</th>
						        		<th style="border: none;width: auto;"class="dates coupons" id="Use_coupons">
						        			<i>使用</i>
						        			<input type="text" name="" id="" value="" class="dt startTime" onclick="createDate(this)" onfocus="createDate(this)" placeholder="开始时间"  style="max-width:100px ;" />
					        				<i>到</i>
						        			<input type="text" name="" id="" value="" class="dt endTime" onclick="createDate(this)" onfocus="createDate(this)" placeholder="结束时间"   style="max-width:100px ;"/>			        			
						        		</th>
						        		<th style="width: 2rem;max-width: 200px;border: none;"><i>仅查看</i><input type="text" name=""id="coupos" class="names" value="" style="text-align:left"/><i>券</i></th>
						        		<th style="border: none;width: 1rem;max-width: 100px;">
						        			<a href="javascript:;"onclick="dateJudge(this)" id="inquire" class="inquire">查询</a>
						        		</th>
						        		<th style="border: none;width: 1rem;max-width: 100px;">
						        			<a href="javascript:;" id="cancel_query"onclick="cancelQuery(this)" style="background-color: #ccc;cursor: no-drop;">取消查询</a>
						        		</th>
						        		<th style="border: none;width: 1rem;max-width: 100px;">
						        			<label for="zclip-ZeroClipboardMovie_1"><a href="javascript:;" class="ticket" onclick="javascript:method1(ticket)">导出</a></label>
						        		</th>
						        	</tr>
						            <tr>
						            	<th>券ID</th>
						            	<th>券名称</th>
						            	<th>券发放人数</th>
						            	<th>券发放张数</th>	
						            	<th>日期</th>	
						            	<th>投资总金额</th>	
						            	<th>投资人数</th>	
						            	<th>用券投资额</th>	
						            	<th>用券投资人数</th>
						            	<th>转化率</th>
						            	<th>券使用张数</th>
						            	<th>券使用率</th>
						            	<th>折扣金额</th>
						            	<th>加息券成本</th>
						            	<th>券成本</th>
						            	<th>短信成本</th>
						            	<th>营销总成本</th>
						            	<th>用券人全部投资金额</th>
						            	<th>查询日期总交易额</th>
						            	<th>交易占比</th>
						            </tr>
						        </thead>
						    </table>
						</div>
						<!--  end table header  -->
						<!--  start table content  -->
						<div class="table-body">
						 	<table class="use_situation" id="ticket">
						       	<colgroup><col /><col /><col /><col /><col /><col /><col /><col /><col/></colgroup>
						        <tbody>						        	
						        </tbody>						            
							</table>
						</div>	 
				  	</section>	
					<!--  end table content  -->  		
					<!-- end use situation number  -->
				</section>
				<!-- start trading situation amount -->
				<section class="table_content "id="trading_situation">
				<!--  start table header  -->	
					<section class="table_scroll">	    
						<div class="table-head">
						    <table>
						        <colgroup><col /><col /><col /><col /><col /><col /><col /><col /><col /></colgroup>
						        <thead>
						        	<tr class="searchTR">
						        		<th style="border: none;"><i>从</i>
						        			<input type="text" name="" id="" value=""class="dt startTime" onclick="createDate(this)" onfocus="createDate(this)" placeholder="开始时间" />
					        			</th>
						        		<th style="border: none;"class="dates">
						        			<i>到</i>
						        			<input type="text" name="" id="" value="" class="dt endTime" onclick="createDate(this)" onfocus="createDate(this)" placeholder="结束时间" />			        			
						        		</th>
						        		<th colspan="2" style="width: 2rem;max-width: 200px;border: none;"><i>仅查看</i><input type="text" name="" id="procs" class="names" value="" /><i>产品</i></th>
						        		<th style="border: none;width: 1rem;max-width: 100px;">
						        			<a href="javascript:;" onclick="dateJudge(this)" id="inquire" class="inquire">查询</a>
						        		</th>
						        		<th style="border: none;width: 1rem;max-width: 100px;">
						        			<a href="javascript:;" id="cancel_query"onclick="cancelQuery(this)" style="background-color: #ccc;cursor: no-drop;">取消查询</a>
						        		</th>
						        		<th style="border: none;width: 1rem;max-width: 100px;">
						        			<label for="ZeroClipboardMovie_2"><a href="javascript:;" class="trading"onclick="javascript:method1(trading)">导出</a></label>
						        		</th>
						        	</tr>
						            <tr>
						            	<th>产品名称</th>
						            	<th>产品利率</th>	
						            	<th>投资天数</th>	
						            	<th>最早交易时间</th>	
						            	<th>最近交易时间</th>	
						            	<th>订单数</th>	
						            	<th>交易用户数</th>	
						            	<th>交易金额</th>	
						            	<th>现金券抵用券</th>
						            	<th>投资收益总额</th>
						            	<th>加息券加息金额</th>
						            </tr>
						        </thead>
						    </table>
						</div>
						<!--  end table header  -->
						<!--  start table content  -->
						<div class="table-body">
						 	<table class="trading_situation" id="trading">
						       	<colgroup><col /><col /><col /><col /><col /><col /><col /><col /><col/></colgroup>
						        <tbody></tbody>						            
							</table>
						</div>
					</section>	   		
					<!--  end table content  -->
				</section>
				<!-- end trading situation amount -->	
			</div>
		</article>
		<!--  end the Activities in query -->
    </div>
</div>
<div id="activity_List"></div>
<script src="/js/addtags2.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/event-detail.js"></script>
